### PR TITLE
Issue 41. PailTap should use Hadoop configuration provided to it instead...

### PR DESCRIPTION
**Pull request by kyrill007**
... of always reading the default one.

### CODE REVIEW

**Comment by kyrill007** [comment]
https://github.com/nathanmarz/dfs-datastores/pull/42

**Comment by vmarcinko** [comment]
Great pull requests. I just thought about doing the same few days ago.

**Comment by kyrill007** [comment]
Thanks! Let's hope that somebody accepts it. :-)

**Comment by sorenmacbeth** [comment]
LGTM :+1:

**Pull request merged**
