### PR TITLE
My hack around the fs.default.name issue

### PR DESCRIPTION
**Pull request by sorenmacbeth**
It's not horrible, the only part I'm not crazy about is getting the filesystem from the target in the mapper. It does work for me though, so that's a plus.

### CODE REVIEW

**Comment by sorenmacbeth** [comment]
Also, there isn't really any point in passing a FileSystem object into Consolidator/consolidate at all, since It's resolved from the file path using Utils.getFS() when it's needed.

**Comment by sorenmacbeth** [comment]
Cleaned it up a bit. This is closer to original code, but works across filesystem without messing with fs.default.name

**Comment by sritchie** [comment]
If you revent that last clojars-prepping commit I'll go ahead and merge this in! I'll also add you prominently to a new "CONTRIBUTORS" list. You, sir, are the Pailmaster.

**Comment by sorenmacbeth** [comment]
Done and done!

**Comment by sritchie** [comment]
Released as `[backtype/dfs-datastores "1.1.1"]`.

**Pull request merged**
