### PR TITLE
Modify version checker to disregard paths starting with underscores and dangling versions.

### PR DESCRIPTION
**Pull request by azymnis**
I added a test which passes, though a number of tests in this repo are flaky.

### CODE REVIEW

**Comment by sorenmacbeth** [comment]
LGTM, thanks!

**Comment by sritchie** [comment]
@azymnis, want to publish this internally to see if it works? If so we can do a full release... soren, I think we need to get you added to the backtype group on sonatype.

**Comment by sorenmacbeth** [comment]
@sritchie pretty sure that we did that already. for example, I've published a 1.3.5-SNAPSHOT that we've been using for a good while now.

**Comment by sritchie** [comment]
Nice. Any chance I could get you to push a snapshot for @azymnis ? thanks dude

**Comment by sorenmacbeth** [comment]
done.

On Tue, Aug 27, 2013 at 7:38 PM, Sam Ritchie notifications@github.comwrote:

> Nice. Any chance I could get you to push a snapshot for @azymnishttps://github.com/azymnis? thanks dude
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/nathanmarz/dfs-datastores/pull/37#issuecomment-23386098
> .

## 

http://about.me/soren

**Comment by azymnis** [comment]
@sorenmacbeth @sritchie thanks guys!

**Comment by azymnis** [comment]
@sorenmacbeth is the snapshot version still 1.3.5-SNAPSHOT? Also where is this published?

**Comment by sorenmacbeth** [comment]
Yes, version is still 1.3.5-SNAPSHOT and its hosts at sonatype

On Wednesday, August 28, 2013, Argyris Zymnis wrote:

> @sorenmacbeth https://github.com/sorenmacbeth is the snapshot version
> still 1.3.5-SNAPSHOT? Also where is this published?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/nathanmarz/dfs-datastores/pull/37#issuecomment-23437298
> .

## 

http://about.me/soren

**Comment by azymnis** [comment]
Thanks, I tested the snapshot and it works and solves our problems. @sorenmacbeth is there any chance that you could do a full release? We generally don't like to depend on snapshots in master.

**Comment by sorenmacbeth** [comment]
Yes, I'll try and do a full release of 1.3.5 tonight.

On Wed, Aug 28, 2013 at 2:21 PM, Argyris Zymnis notifications@github.comwrote:

> Thanks, I tested the snapshot and it works and solves our problems.
> @sorenmacbeth https://github.com/sorenmacbeth is there any chance that
> you could do a full release? We generally don't like to depend on snapshots
> in master.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/nathanmarz/dfs-datastores/pull/37#issuecomment-23448725
> .

## 

http://about.me/soren

**Comment by sorenmacbeth** [comment]
1.3.5 has been released!

On Wed, Aug 28, 2013 at 2:38 PM, Soren Macbeth soren@dopeness.org wrote:

> Yes, I'll try and do a full release of 1.3.5 tonight.
> 
> On Wed, Aug 28, 2013 at 2:21 PM, Argyris Zymnis notifications@github.comwrote:
> 
> > Thanks, I tested the snapshot and it works and solves our problems.
> > @sorenmacbeth https://github.com/sorenmacbeth is there any chance that
> > you could do a full release? We generally don't like to depend on snapshots
> > in master.
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/nathanmarz/dfs-datastores/pull/37#issuecomment-23448725
> > .
> 
> ## 
> 
> http://about.me/soren

## 

http://about.me/soren

**Comment by azymnis** [comment]
Thanks man!

**Pull request merged**
