### PR TITLE
Added support for parameterized PailStructures

### PR DESCRIPTION
**Pull request by derrickburns**
Based on 1.3.1 master.  

Added retry of rename requests.

Added backward compatibly implementation of parameterized PailStructures that are serialized by Jackson. 

Added pom.xml file.  Note, you will want to change the version number.

### CODE REVIEW

**Comment by sritchie** [comment]
Hey, quick comment -- I really don't want two build systems, so let's remove the pom.xml. sbt can generate a pom file with "sbt make-pom".

**Comment by sritchie** [comment]
Can you give me a bit more information about these changes?

**Comment by sritchie** [comment]
Also, and sorry that this is a pain, please open this pull request against the "develop" branch -- master is meant to be the current deployed version, while develop is reserved for fully-baked features for the next release.

**Comment by derrickburns** [comment]
I opened a separate Pull Request against the development branch.

**Comment by derrickburns** [comment]
Done.
—

**Pull request closed without merging**
