### PR TITLE
Added support for parameterized PailStructures

### PR DESCRIPTION
**Pull request by derrickburns**
1. Made PailTap#_pailRoot protected instead of private.
2. Added PailTap#getPaths() method to provide paths to all subPail roots.
3. Added Jackson 2.0 annotations to PailStructure to support Jackson serialization.
4. Retry rename() in AbstractPail#close() because failure is costly!
5. Serialize PailStructure into pail.meta files using Jackson 2.0.  This allows PailStructures to be parameterized. This is done in a backward compatible way.  Old meta files with PailStructures that take no arguments still work.  However, new pail.meta files will be created by emitting not just the PailStructure class name, but a Jackson 2.0 serialization of the PailStructure. This is typically very compact, for example:

```

---
format: SequenceFile
structure: '{"@class":"com.rincaro.mapreduce.store.timeseriesstore.TemplateTimeSeriesPailStructure","template":"${type}"}'
args: {}
```

This declares a PailStructure that takes a single argument, "template", with value "${type}".

Here is the corresponding constructor with Jackson 2.0 annotations:

```
    @JsonCreator
    public TemplateTimeSeriesPailStructure( @JsonProperty("template") String template ) {
        mTemplate = template;
    }

    public String getTemplate() {
        return mTemplate;
    }
```
1. Added pom.xml.  If you don't want it, just ignore it. :)

### CODE REVIEW

**Comment by sritchie** [comment]
Hey Derrick, thanks a lot for this. Let me look over this a bit more and make some comments. Re the pom.xml, Just go ahead and add pom.xml back into the .gitignore and this will look good.

**Comment by sritchie** [comment]
Also, not sure why we can't merge?

**Comment by derrickburns** [comment]
Commit c1619b3 also addresses #21

**Comment by sritchie** [comment]
Hey Derrick, sorry for my inactivity -- I'm going to leave this (and future dfs-datastores decisions) up to @nathanmarz, as he's maintaining the library for the release of his new book.

**Comment by derrickburns** [comment]
No problem.

**Comment by kul** [comment]
:+1:

**Comment by sritchie** [comment]
@sorenmacbeth, what do you think? big change here.

**Comment by kul** [comment]
@sorenmacbeth Please sort this out. the number and kind of pull requests already show that this kind of feature is most desirable for api users. :smile:

**Comment by kul** [comment]
The pull request looks like a dead end as it seems that author has developed it into a person project. Whole code organization is changed even the Build files for scala are deleted. although this could have been the most elegant way to support dynamic pail structures.  :cry:  commits can be cherry picked but, seems like rewriting support for Jackson would be more easier!

**Comment by derrickburns** [comment]
Yes, I wrote the pull request. After no action was taken, I dealt with the many other issues that arose. 

Cherry picking the Jackson support would be easy....

—

**Pull request closed without merging**
